name: docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install pip==23.1.2 setuptools==67.7.2 wheel==0.40.0
          pip install virtualenv==20.23.0 tox==4.5.1.1

      - name: install haddock3
        run: pip install -v .

      - name: docs
        run: tox -e docs
